services:
  server:
    image: server-image
    build: server
    environment:
      - DATABASE_URI=database
    ports:
      - "3000:3000"
  client:
    image: client-image
    build: client
    ports:
      - "8080:3000"
  database:
    image: mongo
    ports:
      - "27017:27017"